# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos-hdp"
  config.vm.network "private_network", ip: "192.168.33.12"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  # BUGFIX: remove when upgrading to vagrant 1.8.6+
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "UTC"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1",        "on"]
    vb.customize ["modifyvm", :id, "--nictype1",            "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2",            "virtio"]
  end

  config.vm.provision "shell", path: "scripts/base.sh"

  config.vm.provision "shell", path: "scripts/ambari.sh"

  # Optional: provision the R engine
  # config.vm.provision "shell", path: "scripts/rlang.sh"
end
