# -*- mode: ruby -*-
# vi: set ft=ruby :

MONGODB_VERSION="3.2.7"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "trusty-mongodb"
  config.vm.network "private_network", ip: "192.168.33.12"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "scripts/base.sh"

  config.vm.provision "shell", path: "scripts/mongodb.sh", args: [MONGODB_VERSION]
end
