# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  # BUGFIX: remove when upgrading to vagrant 1.8.6+
  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "UTC"
  end

  # We need one admin node
  config.vm.define "hdp-admin" do |admin|
    admin.vm.hostname = "centos-hdp"
    admin.vm.network :private_network, ip: "192.168.33.12"

    admin.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1",        "on"]
      vb.customize ["modifyvm", :id, "--nictype1",            "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2",            "virtio"]
    end

    admin.vm.provision "shell", path: "scripts/base.sh"

    admin.vm.provision "shell", path: "scripts/ambari.sh"
  end

  # We provision two more nodes
  (1..2).each do |i|
    config.vm.define "hdp-server-#{i}" do |config|
      config.vm.hostname = "centos-hdp-#{i}"
      config.vm.network :private_network, ip: "192.168.33.#{i+12}"

      config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1",        "on"]
        vb.customize ["modifyvm", :id, "--nictype1",            "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2",            "virtio"]
      end

      config.vm.provision "shell", path: "scripts/base.sh"
    end
end
end
