# -*- mode: ruby -*-
# vi: set ft=ruby :

CLOUDERA_CDH_VERSION="5"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "trusty-cdh5"
  config.vm.network "private_network", ip: "192.168.33.11"

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
  end

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "UTC"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "scripts/increase_swap.sh"

  config.vm.provision "shell", path: "scripts/base.sh"

  config.vm.provision "shell", path: "scripts/yarn.sh", args: [CLOUDERA_CDH_VERSION]

  config.vm.provision "shell", path: "scripts/hive.sh"

  config.vm.provision "shell", path: "scripts/impala.sh"

  config.vm.provision "shell", path: "scripts/hbase.sh"

  config.vm.provision "shell", path: "scripts/spark.sh"

  config.vm.provision "shell", path: "scripts/kafka.sh"
end
