# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "trusty-cdh5"
  config.vm.network "private_network", ip: "192.168.33.11"
  
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "scripts/base.sh"

  config.vm.provision "shell", path: "scripts/yarn.sh"

  config.vm.provision "shell", path: "scripts/hive.sh"

  config.vm.provision "shell", path: "scripts/impala.sh"

  config.vm.provision "shell", path: "scripts/hbase.sh"
end
